postgres:
  container_name: AspNetCoreWebApiApp_DB
  image: postgres:9.4.5
  ports:
    - 5432:5432
  environment:
    POSTGRES_DB: oms
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 123123
  restart: always

dotnetcore-demo:
  container_name: AspNetCoreWebApiApp_WEB
  image: dr:5000/dotnetcore-demo
  volumes:
    - ~/Workspace/Projects/AspNetCoreWebApiApp/Config:/root/Config
  links:
    - postgres:pg-host
  ports:
    - 5000:5000
  environment:
    ASPNETCORE_URLS: http://*:5000/
    ASPNETCORE_ENVIRONMENT: Production
  restart: always
